#!/bin/bash
# ============================================================================
# Manual Fix Commands - Run these with sudo
# ============================================================================

echo "Run these commands manually (they require sudo):"
echo ""
echo "# 1. Fix system cuDNN symlink"
echo "sudo ln -sf /usr/lib/aarch64-linux-gnu/libcudnn.so.9 /usr/lib/aarch64-linux-gnu/libcudnn.so.8"
echo ""
echo "# 2. Fix MPI libraries"
echo "sudo ln -sf /usr/lib/aarch64-linux-gnu/libmpi.so.40.30.2 /usr/lib/aarch64-linux-gnu/libmpi.so.20"
echo "sudo ln -sf /usr/lib/aarch64-linux-gnu/libmpi_cxx.so.40 /usr/lib/aarch64-linux-gnu/libmpi_cxx.so.20"
echo ""
echo "# 3. Fix CUDA libraries"
echo "sudo ln -sf /usr/local/cuda-12.6/targets/aarch64-linux/lib/libcufft.so.11 /usr/local/cuda-12.6/targets/aarch64-linux/lib/libcufft.so.10"
echo "sudo ln -sf /usr/local/cuda-12.6/targets/aarch64-linux/lib/libcufft.so.11 /usr/lib/aarch64-linux-gnu/libcufft.so.10"
echo "sudo ln -sf /usr/local/cuda-12.6/targets/aarch64-linux/lib/libcublas.so.12 /usr/local/cuda-12.6/targets/aarch64-linux/lib/libcublas.so.10"
echo "sudo ln -sf /usr/local/cuda-12.6/targets/aarch64-linux/lib/libcublas.so.12 /usr/lib/aarch64-linux-gnu/libcublas.so.10"
echo "sudo ln -sf /usr/local/cuda-12.6/targets/aarch64-linux/lib/libcudart.so.12 /usr/local/cuda-12.6/targets/aarch64-linux/lib/libcudart.so.10"
echo "sudo ln -sf /usr/local/cuda-12.6/targets/aarch64-linux/lib/libcudart.so.12 /usr/local/cuda-12.6/targets/aarch64-linux/lib/libcudart.so.10.2"
echo "sudo ln -sf /usr/local/cuda-12.6/targets/aarch64-linux/lib/libcudart.so.12 /usr/lib/aarch64-linux-gnu/libcudart.so.10"
echo "sudo ln -sf /usr/local/cuda-12.6/targets/aarch64-linux/lib/libcudart.so.12 /usr/lib/aarch64-linux-gnu/libcudart.so.10.2"
echo ""
echo "# 4. Update library cache"
echo "sudo ldconfig"
echo ""
echo "# 5. Set LD_LIBRARY_PATH (add to ~/.bashrc if not already there)"
echo "export LD_LIBRARY_PATH=/usr/local/cuda-12.6/targets/aarch64-linux/lib:\$LD_LIBRARY_PATH"
echo "echo 'export LD_LIBRARY_PATH=/usr/local/cuda-12.6/targets/aarch64-linux/lib:\$LD_LIBRARY_PATH' >> ~/.bashrc"
echo ""
echo "# 6. Try using LD_PRELOAD to force cuDNN 9"
echo "export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libcudnn.so.9"
echo ""
